### ISSUE TITLE
Install node and npm

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii-docker#1]
This would be a useful addition at least for Yii 2.1.

This is related to https://github.com/yiisoft/yii2-docker/issues/7 - but creating different flavours or "production-only" images without build tooling (composer, node, npm)  is a larger task.
It could also be created with https://docs.docker.com/develop/develop-images/multistage-build/

I'd add it.

**Comment by vuquangthinh** [comment]
why did you need node & npm ?
If you want to create SPA, we can create docker-compose.override.yml ?

**Comment by samdark** [comment]
New repo, I think.

**Comment by samdark** [comment]
Done.
