### ISSUE TITLE
404 nginx problem

### ISSUE THREAD

**Issue by Fantom409** [yiisoft/yii-docker#14]
### What steps will reproduce the problem?
copy and changed .env file for Nginx

composer create-project -s dev yiisoft/app /app

Open http://127.0.0.1:8100/

### What is the expected result?

App Welcome page

### What do you get instead?

404 Not Found Nginx page 

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 7.4-fpm
| Operating system | ubuntu 20.04

This problem caused by Nginx config in phundament image - for this repository, web root directory should be set as /app/public, instead, this path is setted as /app/web

**Comment by samdark** [comment]
Fixed now with https://github.com/yiisoft/yii-docker/commit/0a72c6c912ca224ceabe14bef79405dd765ea164?

**Comment by Fantom409** [comment]
> Fixed now with [0a72c6c](https://github.com/yiisoft/yii-docker/commit/0a72c6c912ca224ceabe14bef79405dd765ea164)?

No. `WORKDIR` instruction won't and shouldn't alter Nginx behavior

**Comment by schmunk42** [comment]
I think we should go with a nginx flavour ... nginx added to the PHP image.

like so:
https://github.com/dmstr/docker-php-yii2/blob/master/nginx/Dockerfile-fpm-nginx

@yiisoft/core-developers Agree?

**Comment by samdark** [comment]
Yes.

**Comment by schmunk42** [comment]
WIP here https://github.com/yiisoft/yii-docker/tree/feature/nginx-flavour

**Comment by schmunk42** [comment]
nginx-flavor is available since a while
