### ISSUE TITLE
Package Yii Runner Roadrunner requred ext-sockets

### ISSUE THREAD

**Issue by nikolaev-dm** [yiisoft/yii-docker#24]
Package https://github.com/yiisoft/yii-runner-roadrunner require ext-sockets. Will it be enabled PHP's sockets extension?

**Comment by samdark** [comment]
Do you mean adding it to require of composer.json?

**Comment by nikolaev-dm** [comment]
I meant to include an PHP's sockets extension in the docker image

**Comment by nikolaev-dm** [comment]
![image](https://user-images.githubusercontent.com/52159053/179391833-e38f5b18-e344-43f6-ad11-4849ea585fdb.png)

image: yiisoftware/yii-php:8.1-fpm
I can install an extension based on this image. But is it right? If the package from yiisoft is can not installed in the official image?

**Comment by samdark** [comment]
Right. https://github.com/yiisoft/yii-docker/blob/master/Dockerfile-debian#L9 should help, correct?

**Comment by rustamwin** [comment]
> Right. https://github.com/yiisoft/yii-docker/blob/master/Dockerfile-debian#L9 should help, correct?

Yes.
