### ISSUE TITLE
*-min images does not have mandatory packages

### ISSUE THREAD

**Issue by albertborsos** [yiisoft/yii-docker#37]
### What steps will reproduce the problem?

use `*-min` images with mysql for example.

### What is the expected result?

it works with mysql

### What do you get instead?

it does not work with mysql

### Additional info

| Q                | A
| ---------------- | ---
| Version          | latest
| PHP version      |  8.2
| Operating system | linux

I think the `*-min` images should contain php extensions which are mandatory for the Yii 3.0 framework.

Because these extension installations are in the `dev` stage:

https://github.com/yiisoft/yii-docker/blob/d02870afe83d071a6cfb12f771a3de0a62f4437b/Dockerfile-debian#L33-L55

I think some of these packages should be installed in the `min` stage, and some of them (like xdebug) should be installed in the `dev` stage.

What do you think?

**Comment by schmunk42** [comment]
> I think the *-min images should contain php extensions which are mandatory for the Yii 3.0 framework.

MySQL is not mandatory, you could also use Postgre or several other DBs...
 
If you want a more or less full featured image use the standard ones.
Or install MySQL with the provided one-liner install script.
