### ISSUE TITLE
Remove pre 7.4 images from DockerHub?

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii-docker#4]
### What steps will reproduce the problem?

Try i.e. `yii-project-template` with an 7.3 image.

### What is the expected result?

It should install.

### What do you get instead?

Error: PHP 7.3 not supported

### Additional info

A con is, that there might be people using these outdated images, but since we're in (pre)-alpha stage I'd say it's OK to remove them, to avoid confusion,
PHP 7.4 was freshly pushed today.

**Comment by samdark** [comment]
Yes.

**Comment by schmunk42** [comment]
Done: https://hub.docker.com/repository/docker/yiisoftware/yii-php/tags?page=1
