### ISSUE TITLE
Images with PHP version less than 7.4 should be removed

### ISSUE THREAD

**Issue by Fantom409** [yiisoft/yii-docker#5]
Because yii3 require minimum php 7.4, other images (7.3-fpm, 7.2-fpm, 7.1-fpm,7.3-apache, 7.2-apache, 7.1-apache) is useless

**Comment by roslov** [comment]
Please don't remove them. I use them for other projects, non-Yii based.

**Comment by schmunk42** [comment]
They are removed already (since Dec'19) 

See https://github.com/yiisoft/yii-docker/issues/4

**Comment by Fantom409** [comment]
But I'm able to build services based on deprecated images

**Comment by Fantom409** [comment]
I think I know why this happened because docker doesn't pull remote image and build based on local Dockerfile. So we need to check minumum php version in Dockerfile

**Comment by schmunk42** [comment]
> So we need to check minumum php version in Dockerfile

I do not understand what you mean?

**Comment by Fantom409** [comment]
I mean in [Dockerfile](https://github.com/yiisoft/yii-docker/blob/master/php/Dockerfile-debian) should be added instruction that assert that php version is bigger or equal to 7.4. Something like this:
`RUN php -r "echo PHP_VERSION_ID < 74000;" | echo 'php version is smaller then 7.4' && false
`

**Comment by schmunk42** [comment]
We won't have images lower than 7.4

**Comment by Fantom409** [comment]
Our local [Dockerfile](https://github.com/yiisoft/yii-docker/blob/master/php/Dockerfile-debian) allow to build images with php lower than 7.4. So if you set enviroment variable like this `PHP_BASE_IMAGE_VERSION=7.3-apache`, and run `docker-compose build`, it build successfully, but it shouldn't. Another way to solve this problem is to delete ability to build images from local Dockerfile in docker-compose.yml

**Comment by schmunk42** [comment]
Actually there should be requirement for minimum PHP versions in `composer.json` and `composer install` should fail in build.

eg. https://github.com/yiisoft/db/blob/master/composer.json#L71

but ie. missing here https://github.com/yiisoft/yii-web/blob/master/package.json

CC: @samdark

**Comment by Fantom409** [comment]
> but ie. missing here https://github.com/yiisoft/yii-web/blob/master/package.json

This is npm configuration, not composer

**Comment by schmunk42** [comment]
> > but ie. missing here https://github.com/yiisoft/yii-web/blob/master/package.json
> 
> This is npm configuration, not composer

My bad, sorry.

Regarding the base image version ... you should actually build `FROM yiisoftware/yii-php`.
Personally, I don't think we need the check for <7.4 in the Dockerfile, but feel free to create a PR to discuss this issue.
