### ISSUE TITLE
yarn is missing

### ISSUE THREAD

**Issue by albertborsos** [yiisoft/yii-docker#9]
### What steps will reproduce the problem?

 * clone yii3 application template
 * set up docker
 * log in to shell
 * execute `composer install`

### What is the expected result?

composer install successfully finished

### What do you get instead?

```bash
Package operations: 143 installs, 0 updates, 0 removals
  - Installing foxy/foxy (v1.1.0): Loading from cache

                                          
  [Foxy\Exception\RuntimeException]       
  The binary of "yarn" must be installed  
```

after `npm install -g yarn` composer runs successfully

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 7.4-apache
| Operating system | host OS: MacOS

**Comment by samdark** [comment]
Yes. Should be added...
